### ISSUE TITLE
Solve bbox for asset-scanner indexing

### ISSUE THREAD

**Issue by Mahir-Sparkess** [cedadev/search-futures#128]
The elasticsearch-aggregator needs a generic way to handle bbox:

- how aggregate?
- how to represent bbox in es?

**Comment by Mahir-Sparkess** [comment]
How to represent:

Store the bbox information in properties as:
- `minLon`
- `maxLon`
- `minLat`
- `maxLat`
- OPTIONAL `maxHeight`
- OPTIONAL `minHeight`

es can then aggregate the min and max values and the processor can handle converting the values to a string format.

## Asset
```json
"properties": {
    "minLon": int OR float,
    "maxLon": int OR float,
    "minLat": int OR float,
    "maxLat": int OR float,
    "minHeight": int OR float,
    "maxHeight": int OR float
}
```

## Item
```json
"bbox": [minLon, maxLon, minLat, maxLat, minHeight, maxHeight]
"properties": {
    "minLon": int OR float,
    "maxLon": int OR float,
    "minLat": int OR float,
    "maxLat": int OR float,
    "minHeight": int OR float,
    "maxHeight": int OR float,
}
```

## Collection
```json
"extent": {
    "spatial":{
        "bbox": [minLon, maxLon, minLat, maxLat, minHeight, maxHeight]
    }
}
```

**Comment by Mahir-Sparkess** [comment]
## TO-DO
- [ ] look at the asset-generation stage for locations that geometry/spatial values are pulled and created and update the code to the add the format above into the *properties*?
  - [ ] look at [item-descriptions ](https://github.com/cedadev/item-descriptions) for bbox values
  - [ ] look at [input plugins](https://github.com/cedadev/asset-scanner/tree/master/asset_scanner/plugins/input_plugins) for bbox values
  - [ ] look at [asset-generator](https://github.com/cedadev/asset-generator/tree/main/asset_generator) for bbox values
- [ ] At the aggregation stage and use the above format to create the bbox and geometry values:
  - [ ] item-generator
  - [ ] collection-generator
- [ ] rerun the pipeline with bbox enabled.

**Comment by Mahir-Sparkess** [comment]
- https://github.com/cedadev/asset-generator/pull/26
- https://github.com/cedadev/collection-generator/pull/8
- https://github.com/cedadev/asset-generator/pull/26

**Comment by rhysrevans3** [comment]
I would consider:
```
"bbox": {
    "minLon": int OR float,
    "maxLon": int OR float,
    "minLat": int OR float,
    "maxLat": int OR float,
    "minHeight": int OR float,
    "maxHeight": int OR float,
}
```
or just leaving them in properties then letting the API convert them to a `list`. Same for collection. Rather than duplicating in the Item. The format of ES doesn't really matter as long as we can search on it and convert it to STAC.

**Comment by agstephens** [comment]
Not sure if this helps, but there is also:

```
from numbers import Number
```

Which covers `float` and `int`.

**Comment by agstephens** [comment]
@Mahir-Sparkess: has this issue now been solved?

**Comment by Mahir-Sparkess** [comment]
@agstephens Yep, this is done and can be closed.
