### ISSUE TITLE
Shift indexing approach to push all properties to the asset level and then summarise assets to items and items to collections.

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#87]
# Assets
- [x] Move facet extraction components from the item-generator to the asset-generator workflow
    - Facet extraction workflow
    - Item ID generation function
- [x] Test on small subset of data (faam, cmip)

# Items
- [x] Remove facet extraction elements from workflow
- [x] Create workflow to summarise asset properties to create items 

# Questions
- How do we tidy up orphaned items? (where item IDs change in assets)
- What is the object used to form the aggregations? (currently all workflows use paths, do we need to use item IDs?) This applies to the collection-generator as well.

**Comment by Mahir-Sparkess** [comment]
## Asset-scanner

- https://github.com/cedadev/asset-scanner/pull/26
- `file_input` and `file_output` plugins to text files.
- 'json_out' output plugin to json file as list of dicts. (useful for testing output without capsys)
- ~~Moved `elasticsearch_aggregator` into framework level that is used commonly by item and collection generator.~~ seperated back to items and collections due to differences.
- https://github.com/cedadev/asset-scanner/issues/27

## Asset-generator

- https://github.com/cedadev/asset-generator/pull/21
- Generator properties in asset level and push to output.
- Create a header output that can be sent to the item level as an input. Header output includes item id and filepath.
- Use LRU cache to deduplicate header output

## Collection-generator

- https://github.com/cedadev/collection-generator/pull/6
- ~~elasticsearch_aggregator and co. moved to asset_scanner framework.~~ Elasticsearch_aggregator types and base moved to framework. Aggregator itself kept.
- Added JSON aggregator, only to be used for asset-scanner-example, does not generate extent.

## Item-generator

- https://github.com/cedadev/item-generator/pull/44
- Use the elasticsearch_aggregator to pull asset facet aggregations and merge them to output. Format the datetimes to work with the collection elasticsearch_aggregator.
- Added LRU cache to deduplicate collection ids.
- Added JSON aggregator only to be used by asset-scanner-example.

## Asset-scanner-example

- https://github.com/cedadev/asset-scanner-example/pull/10
- Updated config files to reflect changes to the indexing shift.
- Added collection generator to notebook.
- Updated tests to reflect changes to the output format, use the JSON output for assertion instead of capsys.

## Config updates:

New top-level config options. Only used in `item_generator.face_extractor` and `asset_generator.asset_extractor`

- `header_deduplication`: if enabled, the LRU cache is used to check message creation before header output. If true, passes a delay, else no delayed message. Default `False`
- `CACHE_MAX_SIZE` - maxsize of the LRU cache, default 5 for item-generator, 10 for asset-generator.
- `CACHE_MAX_AGE` - max age for the time-to-live items in the cache in seconds, default 60 in item-generator, 30 for asset-generator
- `DELAY_INCREMENT` - delay increments for each cache catch in milliseconds, default 5000.
- `DELAY_MAX` - maximum delay wait in milliseconds, default 30000

**Comment by Mahir-Sparkess** [comment]
# TO-DO

- [x] JSON output 
- [x] JSON aggregator
- [ ] add comments and code docs to all PR

**Comment by Mahir-Sparkess** [comment]
# TO-DO

- [x] rabbit output plugin
- [ ] maybe look at a popping LRU cache?
- [x] LRU cache: if in cache add delay to header, if not send straight away.
- [x] https://github.com/cedadev/asset-scanner/issues/27

**Comment by Mahir-Sparkess** [comment]
## PRs for Rabbit deduplication:

- https://github.com/cedadev/asset-generator/pull/24/
- https://github.com/cedadev/item-generator/pull/48/
- https://github.com/cedadev/asset-scanner/pull/32/

if deduplication enabled, if `id` is in the cache, create kwargs `deduplicate=True` and `id=object_id`. this is then used by rabbit, standard out, or any other output plugin.

if deduplication is false, don’t check the LRU cache *OR* if deduplication enabled and if `id` is not in the LRU cache, then pass `deduplicate=False` `id=object_id` to the output.

The `rabbitmq_out` adds a delay, default 30s, if deduplicate is true in the kwargs and passes the `x-message-deduplication` to the header with the `id`. This will do a rabbit side deduplication handled by the [rabbit plugin](https://github.com/noxdafox/rabbitmq-message-deduplication)

TODO: will need to add deduplication to the other output plugins i.e. file_out, standard_out
