### ISSUE TITLE
Create an initContainer to provide the vocabs for the Vocab API

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#99]
The Vocab API loads the output from the [vocab generation script](https://github.com/cedadev/stac-vocab).

In the first instance, we relied on this file being present at deployment. In reality, the API application will be relatively stable and we will want to keep adding to the vocab content. We want an automated build and re-deploy process but don't need to rebuild the application.

The vocabularies are configuration fed into the application at startup, thus it makes sense to use an [initContainer](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/). Essentially, the vocabularies are turned into their own, lightweight container and are mounted to the application at deployment. 

CCI Thredds Server Follows this pattern:
https://breezy.badc.rl.ac.uk/cci-odp/cci-odp-data-deploy/-/blob/master/conf/common.yaml#L71 
https://breezy.badc.rl.ac.uk/cci-odp/cci_odp_catalog

For CCI, the XML catalogs are copied into the application container on startup. 

We should do the same with the vocabs. 
This also means that if the vocabs change, then we can automatically trigger an update to the API service.

# Task:

- [ ] Create a CI job (perhaps on a schedule/or just if the configuration has been updated.) to build the `ceda.xml` file.
- [x] Create a CI Job to create a data container which contains this `ceda.xml` file and push to the [CEDA Registry](registry.ceda.ac.uk)
- [x] Modify the API deployment to use an initContainer to "mount" the `ceda.xml` file.

**Comment by agstephens** [comment]
@agstephens and @rhysrevans3: we should work exactly why Richard wanted an `initContainer` to perform the function of re-building the vocab content. Why can't it just be a routine check done by the main service itself - and a simple: `onChange=reload_vocabs()`.
